import { z } from "zod";
export declare const AustralianState: z.ZodEnum<["NSW", "VIC", "QLD", "WA", "SA", "TAS", "NT", "ACT"]>;
export type AustralianState = z.infer<typeof AustralianState>;
export declare const DataSource: z.ZodEnum<["DOMAIN", "REALESTATE", "CORELOGIC", "ABS", "RBA", "MANUAL"]>;
export type DataSource = z.infer<typeof DataSource>;
export declare const ListingStatus: z.ZodEnum<["ACTIVE", "UNDER_CONTRACT", "SOLD", "WITHDRAWN", "OFF_MARKET"]>;
export type ListingStatus = z.infer<typeof ListingStatus>;
export declare const PropertyType: z.ZodEnum<["house", "apartment", "unit", "townhouse", "villa", "land", "rural", "commercial", "other"]>;
export type PropertyType = z.infer<typeof PropertyType>;
export declare const ListingType: z.ZodEnum<["sale", "rent", "sold"]>;
export type ListingType = z.infer<typeof ListingType>;
export declare const PropertyAddressSchema: z.ZodObject<{
    streetNumber: z.ZodOptional<z.ZodString>;
    streetName: z.ZodOptional<z.ZodString>;
    streetType: z.ZodOptional<z.ZodString>;
    suburb: z.ZodString;
    state: z.ZodEnum<["NSW", "VIC", "QLD", "WA", "SA", "TAS", "NT", "ACT"]>;
    postcode: z.ZodString;
    displayAddress: z.ZodString;
    latitude: z.ZodOptional<z.ZodNumber>;
    longitude: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    suburb: string;
    state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
    postcode: string;
    displayAddress: string;
    streetNumber?: string | undefined;
    streetName?: string | undefined;
    streetType?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
}, {
    suburb: string;
    state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
    postcode: string;
    displayAddress: string;
    streetNumber?: string | undefined;
    streetName?: string | undefined;
    streetType?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
}>;
export type PropertyAddress = z.infer<typeof PropertyAddressSchema>;
export declare const PropertyFeaturesSchema: z.ZodObject<{
    bedrooms: z.ZodOptional<z.ZodNumber>;
    bathrooms: z.ZodOptional<z.ZodNumber>;
    parkingSpaces: z.ZodOptional<z.ZodNumber>;
    landSize: z.ZodOptional<z.ZodNumber>;
    buildingSize: z.ZodOptional<z.ZodNumber>;
    propertyType: z.ZodOptional<z.ZodEnum<["house", "apartment", "unit", "townhouse", "villa", "land", "rural", "commercial", "other"]>>;
    features: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    bedrooms?: number | undefined;
    bathrooms?: number | undefined;
    parkingSpaces?: number | undefined;
    landSize?: number | undefined;
    buildingSize?: number | undefined;
    propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
    features?: string[] | undefined;
}, {
    bedrooms?: number | undefined;
    bathrooms?: number | undefined;
    parkingSpaces?: number | undefined;
    landSize?: number | undefined;
    buildingSize?: number | undefined;
    propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
    features?: string[] | undefined;
}>;
export type PropertyFeatures = z.infer<typeof PropertyFeaturesSchema>;
export declare const PropertyListingSchema: z.ZodObject<{
    externalId: z.ZodString;
    source: z.ZodEnum<["DOMAIN", "REALESTATE", "CORELOGIC", "ABS", "RBA", "MANUAL"]>;
    sourceUrl: z.ZodOptional<z.ZodString>;
    address: z.ZodObject<{
        streetNumber: z.ZodOptional<z.ZodString>;
        streetName: z.ZodOptional<z.ZodString>;
        streetType: z.ZodOptional<z.ZodString>;
        suburb: z.ZodString;
        state: z.ZodEnum<["NSW", "VIC", "QLD", "WA", "SA", "TAS", "NT", "ACT"]>;
        postcode: z.ZodString;
        displayAddress: z.ZodString;
        latitude: z.ZodOptional<z.ZodNumber>;
        longitude: z.ZodOptional<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        suburb: string;
        state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
        postcode: string;
        displayAddress: string;
        streetNumber?: string | undefined;
        streetName?: string | undefined;
        streetType?: string | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
    }, {
        suburb: string;
        state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
        postcode: string;
        displayAddress: string;
        streetNumber?: string | undefined;
        streetName?: string | undefined;
        streetType?: string | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
    }>;
    features: z.ZodOptional<z.ZodObject<{
        bedrooms: z.ZodOptional<z.ZodNumber>;
        bathrooms: z.ZodOptional<z.ZodNumber>;
        parkingSpaces: z.ZodOptional<z.ZodNumber>;
        landSize: z.ZodOptional<z.ZodNumber>;
        buildingSize: z.ZodOptional<z.ZodNumber>;
        propertyType: z.ZodOptional<z.ZodEnum<["house", "apartment", "unit", "townhouse", "villa", "land", "rural", "commercial", "other"]>>;
        features: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    }, "strip", z.ZodTypeAny, {
        bedrooms?: number | undefined;
        bathrooms?: number | undefined;
        parkingSpaces?: number | undefined;
        landSize?: number | undefined;
        buildingSize?: number | undefined;
        propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
        features?: string[] | undefined;
    }, {
        bedrooms?: number | undefined;
        bathrooms?: number | undefined;
        parkingSpaces?: number | undefined;
        landSize?: number | undefined;
        buildingSize?: number | undefined;
        propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
        features?: string[] | undefined;
    }>>;
    price: z.ZodOptional<z.ZodString>;
    priceValue: z.ZodOptional<z.ZodNumber>;
    priceFrom: z.ZodOptional<z.ZodNumber>;
    priceTo: z.ZodOptional<z.ZodNumber>;
    listingType: z.ZodEnum<["sale", "rent", "sold"]>;
    listingStatus: z.ZodOptional<z.ZodEnum<["ACTIVE", "UNDER_CONTRACT", "SOLD", "WITHDRAWN", "OFF_MARKET"]>>;
    headline: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    images: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    agentName: z.ZodOptional<z.ZodString>;
    agentPhone: z.ZodOptional<z.ZodString>;
    agencyName: z.ZodOptional<z.ZodString>;
    listedDate: z.ZodOptional<z.ZodString>;
    auctionDate: z.ZodOptional<z.ZodString>;
    inspectionTimes: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    scrapedAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    externalId: string;
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    address: {
        suburb: string;
        state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
        postcode: string;
        displayAddress: string;
        streetNumber?: string | undefined;
        streetName?: string | undefined;
        streetType?: string | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
    };
    listingType: "sale" | "rent" | "sold";
    scrapedAt: string;
    features?: {
        bedrooms?: number | undefined;
        bathrooms?: number | undefined;
        parkingSpaces?: number | undefined;
        landSize?: number | undefined;
        buildingSize?: number | undefined;
        propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
        features?: string[] | undefined;
    } | undefined;
    sourceUrl?: string | undefined;
    price?: string | undefined;
    priceValue?: number | undefined;
    priceFrom?: number | undefined;
    priceTo?: number | undefined;
    listingStatus?: "ACTIVE" | "UNDER_CONTRACT" | "SOLD" | "WITHDRAWN" | "OFF_MARKET" | undefined;
    headline?: string | undefined;
    description?: string | undefined;
    images?: string[] | undefined;
    agentName?: string | undefined;
    agentPhone?: string | undefined;
    agencyName?: string | undefined;
    listedDate?: string | undefined;
    auctionDate?: string | undefined;
    inspectionTimes?: string[] | undefined;
}, {
    externalId: string;
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    address: {
        suburb: string;
        state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
        postcode: string;
        displayAddress: string;
        streetNumber?: string | undefined;
        streetName?: string | undefined;
        streetType?: string | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
    };
    listingType: "sale" | "rent" | "sold";
    scrapedAt: string;
    features?: {
        bedrooms?: number | undefined;
        bathrooms?: number | undefined;
        parkingSpaces?: number | undefined;
        landSize?: number | undefined;
        buildingSize?: number | undefined;
        propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
        features?: string[] | undefined;
    } | undefined;
    sourceUrl?: string | undefined;
    price?: string | undefined;
    priceValue?: number | undefined;
    priceFrom?: number | undefined;
    priceTo?: number | undefined;
    listingStatus?: "ACTIVE" | "UNDER_CONTRACT" | "SOLD" | "WITHDRAWN" | "OFF_MARKET" | undefined;
    headline?: string | undefined;
    description?: string | undefined;
    images?: string[] | undefined;
    agentName?: string | undefined;
    agentPhone?: string | undefined;
    agencyName?: string | undefined;
    listedDate?: string | undefined;
    auctionDate?: string | undefined;
    inspectionTimes?: string[] | undefined;
}>;
export type PropertyListing = z.infer<typeof PropertyListingSchema>;
export declare const PropertySearchParamsSchema: z.ZodObject<{
    suburbs: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    state: z.ZodOptional<z.ZodEnum<["NSW", "VIC", "QLD", "WA", "SA", "TAS", "NT", "ACT"]>>;
    postcode: z.ZodOptional<z.ZodString>;
    minPrice: z.ZodOptional<z.ZodNumber>;
    maxPrice: z.ZodOptional<z.ZodNumber>;
    minBeds: z.ZodOptional<z.ZodNumber>;
    maxBeds: z.ZodOptional<z.ZodNumber>;
    minBaths: z.ZodOptional<z.ZodNumber>;
    propertyTypes: z.ZodOptional<z.ZodArray<z.ZodEnum<["house", "apartment", "unit", "townhouse", "villa", "land", "rural", "commercial", "other"]>, "many">>;
    listingType: z.ZodDefault<z.ZodEnum<["sale", "rent", "sold"]>>;
    includesSurrounding: z.ZodOptional<z.ZodBoolean>;
    page: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    listingType: "sale" | "rent" | "sold";
    page: number;
    state?: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT" | undefined;
    postcode?: string | undefined;
    suburbs?: string[] | undefined;
    minPrice?: number | undefined;
    maxPrice?: number | undefined;
    minBeds?: number | undefined;
    maxBeds?: number | undefined;
    minBaths?: number | undefined;
    propertyTypes?: ("house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other")[] | undefined;
    includesSurrounding?: boolean | undefined;
}, {
    state?: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT" | undefined;
    postcode?: string | undefined;
    listingType?: "sale" | "rent" | "sold" | undefined;
    suburbs?: string[] | undefined;
    minPrice?: number | undefined;
    maxPrice?: number | undefined;
    minBeds?: number | undefined;
    maxBeds?: number | undefined;
    minBaths?: number | undefined;
    propertyTypes?: ("house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other")[] | undefined;
    includesSurrounding?: boolean | undefined;
    page?: number | undefined;
}>;
export type PropertySearchParams = z.infer<typeof PropertySearchParamsSchema>;
export declare const PropertySearchResultsSchema: z.ZodObject<{
    listings: z.ZodArray<z.ZodObject<{
        externalId: z.ZodString;
        source: z.ZodEnum<["DOMAIN", "REALESTATE", "CORELOGIC", "ABS", "RBA", "MANUAL"]>;
        sourceUrl: z.ZodOptional<z.ZodString>;
        address: z.ZodObject<{
            streetNumber: z.ZodOptional<z.ZodString>;
            streetName: z.ZodOptional<z.ZodString>;
            streetType: z.ZodOptional<z.ZodString>;
            suburb: z.ZodString;
            state: z.ZodEnum<["NSW", "VIC", "QLD", "WA", "SA", "TAS", "NT", "ACT"]>;
            postcode: z.ZodString;
            displayAddress: z.ZodString;
            latitude: z.ZodOptional<z.ZodNumber>;
            longitude: z.ZodOptional<z.ZodNumber>;
        }, "strip", z.ZodTypeAny, {
            suburb: string;
            state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
            postcode: string;
            displayAddress: string;
            streetNumber?: string | undefined;
            streetName?: string | undefined;
            streetType?: string | undefined;
            latitude?: number | undefined;
            longitude?: number | undefined;
        }, {
            suburb: string;
            state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
            postcode: string;
            displayAddress: string;
            streetNumber?: string | undefined;
            streetName?: string | undefined;
            streetType?: string | undefined;
            latitude?: number | undefined;
            longitude?: number | undefined;
        }>;
        features: z.ZodOptional<z.ZodObject<{
            bedrooms: z.ZodOptional<z.ZodNumber>;
            bathrooms: z.ZodOptional<z.ZodNumber>;
            parkingSpaces: z.ZodOptional<z.ZodNumber>;
            landSize: z.ZodOptional<z.ZodNumber>;
            buildingSize: z.ZodOptional<z.ZodNumber>;
            propertyType: z.ZodOptional<z.ZodEnum<["house", "apartment", "unit", "townhouse", "villa", "land", "rural", "commercial", "other"]>>;
            features: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        }, "strip", z.ZodTypeAny, {
            bedrooms?: number | undefined;
            bathrooms?: number | undefined;
            parkingSpaces?: number | undefined;
            landSize?: number | undefined;
            buildingSize?: number | undefined;
            propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
            features?: string[] | undefined;
        }, {
            bedrooms?: number | undefined;
            bathrooms?: number | undefined;
            parkingSpaces?: number | undefined;
            landSize?: number | undefined;
            buildingSize?: number | undefined;
            propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
            features?: string[] | undefined;
        }>>;
        price: z.ZodOptional<z.ZodString>;
        priceValue: z.ZodOptional<z.ZodNumber>;
        priceFrom: z.ZodOptional<z.ZodNumber>;
        priceTo: z.ZodOptional<z.ZodNumber>;
        listingType: z.ZodEnum<["sale", "rent", "sold"]>;
        listingStatus: z.ZodOptional<z.ZodEnum<["ACTIVE", "UNDER_CONTRACT", "SOLD", "WITHDRAWN", "OFF_MARKET"]>>;
        headline: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodString>;
        images: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        agentName: z.ZodOptional<z.ZodString>;
        agentPhone: z.ZodOptional<z.ZodString>;
        agencyName: z.ZodOptional<z.ZodString>;
        listedDate: z.ZodOptional<z.ZodString>;
        auctionDate: z.ZodOptional<z.ZodString>;
        inspectionTimes: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        scrapedAt: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        externalId: string;
        source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
        address: {
            suburb: string;
            state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
            postcode: string;
            displayAddress: string;
            streetNumber?: string | undefined;
            streetName?: string | undefined;
            streetType?: string | undefined;
            latitude?: number | undefined;
            longitude?: number | undefined;
        };
        listingType: "sale" | "rent" | "sold";
        scrapedAt: string;
        features?: {
            bedrooms?: number | undefined;
            bathrooms?: number | undefined;
            parkingSpaces?: number | undefined;
            landSize?: number | undefined;
            buildingSize?: number | undefined;
            propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
            features?: string[] | undefined;
        } | undefined;
        sourceUrl?: string | undefined;
        price?: string | undefined;
        priceValue?: number | undefined;
        priceFrom?: number | undefined;
        priceTo?: number | undefined;
        listingStatus?: "ACTIVE" | "UNDER_CONTRACT" | "SOLD" | "WITHDRAWN" | "OFF_MARKET" | undefined;
        headline?: string | undefined;
        description?: string | undefined;
        images?: string[] | undefined;
        agentName?: string | undefined;
        agentPhone?: string | undefined;
        agencyName?: string | undefined;
        listedDate?: string | undefined;
        auctionDate?: string | undefined;
        inspectionTimes?: string[] | undefined;
    }, {
        externalId: string;
        source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
        address: {
            suburb: string;
            state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
            postcode: string;
            displayAddress: string;
            streetNumber?: string | undefined;
            streetName?: string | undefined;
            streetType?: string | undefined;
            latitude?: number | undefined;
            longitude?: number | undefined;
        };
        listingType: "sale" | "rent" | "sold";
        scrapedAt: string;
        features?: {
            bedrooms?: number | undefined;
            bathrooms?: number | undefined;
            parkingSpaces?: number | undefined;
            landSize?: number | undefined;
            buildingSize?: number | undefined;
            propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
            features?: string[] | undefined;
        } | undefined;
        sourceUrl?: string | undefined;
        price?: string | undefined;
        priceValue?: number | undefined;
        priceFrom?: number | undefined;
        priceTo?: number | undefined;
        listingStatus?: "ACTIVE" | "UNDER_CONTRACT" | "SOLD" | "WITHDRAWN" | "OFF_MARKET" | undefined;
        headline?: string | undefined;
        description?: string | undefined;
        images?: string[] | undefined;
        agentName?: string | undefined;
        agentPhone?: string | undefined;
        agencyName?: string | undefined;
        listedDate?: string | undefined;
        auctionDate?: string | undefined;
        inspectionTimes?: string[] | undefined;
    }>, "many">;
    totalCount: z.ZodNumber;
    page: z.ZodNumber;
    pageSize: z.ZodNumber;
    hasMore: z.ZodBoolean;
}, "strip", z.ZodTypeAny, {
    page: number;
    listings: {
        externalId: string;
        source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
        address: {
            suburb: string;
            state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
            postcode: string;
            displayAddress: string;
            streetNumber?: string | undefined;
            streetName?: string | undefined;
            streetType?: string | undefined;
            latitude?: number | undefined;
            longitude?: number | undefined;
        };
        listingType: "sale" | "rent" | "sold";
        scrapedAt: string;
        features?: {
            bedrooms?: number | undefined;
            bathrooms?: number | undefined;
            parkingSpaces?: number | undefined;
            landSize?: number | undefined;
            buildingSize?: number | undefined;
            propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
            features?: string[] | undefined;
        } | undefined;
        sourceUrl?: string | undefined;
        price?: string | undefined;
        priceValue?: number | undefined;
        priceFrom?: number | undefined;
        priceTo?: number | undefined;
        listingStatus?: "ACTIVE" | "UNDER_CONTRACT" | "SOLD" | "WITHDRAWN" | "OFF_MARKET" | undefined;
        headline?: string | undefined;
        description?: string | undefined;
        images?: string[] | undefined;
        agentName?: string | undefined;
        agentPhone?: string | undefined;
        agencyName?: string | undefined;
        listedDate?: string | undefined;
        auctionDate?: string | undefined;
        inspectionTimes?: string[] | undefined;
    }[];
    totalCount: number;
    pageSize: number;
    hasMore: boolean;
}, {
    page: number;
    listings: {
        externalId: string;
        source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
        address: {
            suburb: string;
            state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
            postcode: string;
            displayAddress: string;
            streetNumber?: string | undefined;
            streetName?: string | undefined;
            streetType?: string | undefined;
            latitude?: number | undefined;
            longitude?: number | undefined;
        };
        listingType: "sale" | "rent" | "sold";
        scrapedAt: string;
        features?: {
            bedrooms?: number | undefined;
            bathrooms?: number | undefined;
            parkingSpaces?: number | undefined;
            landSize?: number | undefined;
            buildingSize?: number | undefined;
            propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
            features?: string[] | undefined;
        } | undefined;
        sourceUrl?: string | undefined;
        price?: string | undefined;
        priceValue?: number | undefined;
        priceFrom?: number | undefined;
        priceTo?: number | undefined;
        listingStatus?: "ACTIVE" | "UNDER_CONTRACT" | "SOLD" | "WITHDRAWN" | "OFF_MARKET" | undefined;
        headline?: string | undefined;
        description?: string | undefined;
        images?: string[] | undefined;
        agentName?: string | undefined;
        agentPhone?: string | undefined;
        agencyName?: string | undefined;
        listedDate?: string | undefined;
        auctionDate?: string | undefined;
        inspectionTimes?: string[] | undefined;
    }[];
    totalCount: number;
    pageSize: number;
    hasMore: boolean;
}>;
export type PropertySearchResults = z.infer<typeof PropertySearchResultsSchema>;
export declare const SuburbStatsSchema: z.ZodObject<{
    suburb: z.ZodString;
    state: z.ZodEnum<["NSW", "VIC", "QLD", "WA", "SA", "TAS", "NT", "ACT"]>;
    postcode: z.ZodString;
    source: z.ZodEnum<["DOMAIN", "REALESTATE", "CORELOGIC", "ABS", "RBA", "MANUAL"]>;
    medianPrice: z.ZodOptional<z.ZodNumber>;
    medianRent: z.ZodOptional<z.ZodNumber>;
    grossYield: z.ZodOptional<z.ZodNumber>;
    vacancyRate: z.ZodOptional<z.ZodNumber>;
    daysOnMarket: z.ZodOptional<z.ZodNumber>;
    annualGrowth: z.ZodOptional<z.ZodNumber>;
    fiveYearGrowth: z.ZodOptional<z.ZodNumber>;
    population: z.ZodOptional<z.ZodNumber>;
    medianIncome: z.ZodOptional<z.ZodNumber>;
    ownerOccupied: z.ZodOptional<z.ZodNumber>;
    renters: z.ZodOptional<z.ZodNumber>;
    updatedAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    suburb: string;
    state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
    postcode: string;
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    updatedAt: string;
    medianPrice?: number | undefined;
    medianRent?: number | undefined;
    grossYield?: number | undefined;
    vacancyRate?: number | undefined;
    daysOnMarket?: number | undefined;
    annualGrowth?: number | undefined;
    fiveYearGrowth?: number | undefined;
    population?: number | undefined;
    medianIncome?: number | undefined;
    ownerOccupied?: number | undefined;
    renters?: number | undefined;
}, {
    suburb: string;
    state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
    postcode: string;
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    updatedAt: string;
    medianPrice?: number | undefined;
    medianRent?: number | undefined;
    grossYield?: number | undefined;
    vacancyRate?: number | undefined;
    daysOnMarket?: number | undefined;
    annualGrowth?: number | undefined;
    fiveYearGrowth?: number | undefined;
    population?: number | undefined;
    medianIncome?: number | undefined;
    ownerOccupied?: number | undefined;
    renters?: number | undefined;
}>;
export type SuburbStats = z.infer<typeof SuburbStatsSchema>;
export declare const AgentSchema: z.ZodObject<{
    externalId: z.ZodString;
    source: z.ZodEnum<["DOMAIN", "REALESTATE", "CORELOGIC", "ABS", "RBA", "MANUAL"]>;
    name: z.ZodString;
    email: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    photoUrl: z.ZodOptional<z.ZodString>;
    agencyId: z.ZodOptional<z.ZodString>;
    agencyName: z.ZodOptional<z.ZodString>;
    profileUrl: z.ZodOptional<z.ZodString>;
    salesCount: z.ZodOptional<z.ZodNumber>;
    reviewsCount: z.ZodOptional<z.ZodNumber>;
    rating: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    externalId: string;
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    name: string;
    agencyName?: string | undefined;
    email?: string | undefined;
    phone?: string | undefined;
    photoUrl?: string | undefined;
    agencyId?: string | undefined;
    profileUrl?: string | undefined;
    salesCount?: number | undefined;
    reviewsCount?: number | undefined;
    rating?: number | undefined;
}, {
    externalId: string;
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    name: string;
    agencyName?: string | undefined;
    email?: string | undefined;
    phone?: string | undefined;
    photoUrl?: string | undefined;
    agencyId?: string | undefined;
    profileUrl?: string | undefined;
    salesCount?: number | undefined;
    reviewsCount?: number | undefined;
    rating?: number | undefined;
}>;
export type Agent = z.infer<typeof AgentSchema>;
export declare const AgencySchema: z.ZodObject<{
    externalId: z.ZodString;
    source: z.ZodEnum<["DOMAIN", "REALESTATE", "CORELOGIC", "ABS", "RBA", "MANUAL"]>;
    name: z.ZodString;
    logoUrl: z.ZodOptional<z.ZodString>;
    address: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    website: z.ZodOptional<z.ZodString>;
    profileUrl: z.ZodOptional<z.ZodString>;
    activeListings: z.ZodOptional<z.ZodNumber>;
    soldListings: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    externalId: string;
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    name: string;
    address?: string | undefined;
    phone?: string | undefined;
    profileUrl?: string | undefined;
    logoUrl?: string | undefined;
    website?: string | undefined;
    activeListings?: number | undefined;
    soldListings?: number | undefined;
}, {
    externalId: string;
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    name: string;
    address?: string | undefined;
    phone?: string | undefined;
    profileUrl?: string | undefined;
    logoUrl?: string | undefined;
    website?: string | undefined;
    activeListings?: number | undefined;
    soldListings?: number | undefined;
}>;
export type Agency = z.infer<typeof AgencySchema>;
export declare const SaleRecordSchema: z.ZodObject<{
    externalId: z.ZodOptional<z.ZodString>;
    source: z.ZodEnum<["DOMAIN", "REALESTATE", "CORELOGIC", "ABS", "RBA", "MANUAL"]>;
    address: z.ZodString;
    suburb: z.ZodString;
    state: z.ZodEnum<["NSW", "VIC", "QLD", "WA", "SA", "TAS", "NT", "ACT"]>;
    postcode: z.ZodString;
    propertyType: z.ZodOptional<z.ZodEnum<["house", "apartment", "unit", "townhouse", "villa", "land", "rural", "commercial", "other"]>>;
    saleDate: z.ZodString;
    salePrice: z.ZodNumber;
    saleType: z.ZodOptional<z.ZodString>;
    bedrooms: z.ZodOptional<z.ZodNumber>;
    bathrooms: z.ZodOptional<z.ZodNumber>;
    landSize: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    suburb: string;
    state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
    postcode: string;
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    address: string;
    saleDate: string;
    salePrice: number;
    bedrooms?: number | undefined;
    bathrooms?: number | undefined;
    landSize?: number | undefined;
    propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
    externalId?: string | undefined;
    saleType?: string | undefined;
}, {
    suburb: string;
    state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
    postcode: string;
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    address: string;
    saleDate: string;
    salePrice: number;
    bedrooms?: number | undefined;
    bathrooms?: number | undefined;
    landSize?: number | undefined;
    propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
    externalId?: string | undefined;
    saleType?: string | undefined;
}>;
export type SaleRecord = z.infer<typeof SaleRecordSchema>;
export declare const AuctionResultSchema: z.ZodObject<{
    externalId: z.ZodOptional<z.ZodString>;
    source: z.ZodEnum<["DOMAIN", "REALESTATE", "CORELOGIC", "ABS", "RBA", "MANUAL"]>;
    address: z.ZodString;
    suburb: z.ZodString;
    state: z.ZodEnum<["NSW", "VIC", "QLD", "WA", "SA", "TAS", "NT", "ACT"]>;
    auctionDate: z.ZodString;
    result: z.ZodEnum<["sold_at_auction", "sold_before_auction", "sold_after_auction", "passed_in", "withdrawn"]>;
    guidePrice: z.ZodOptional<z.ZodNumber>;
    soldPrice: z.ZodOptional<z.ZodNumber>;
    propertyType: z.ZodOptional<z.ZodEnum<["house", "apartment", "unit", "townhouse", "villa", "land", "rural", "commercial", "other"]>>;
}, "strip", z.ZodTypeAny, {
    suburb: string;
    state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    address: string;
    auctionDate: string;
    result: "sold_at_auction" | "sold_before_auction" | "sold_after_auction" | "passed_in" | "withdrawn";
    propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
    externalId?: string | undefined;
    guidePrice?: number | undefined;
    soldPrice?: number | undefined;
}, {
    suburb: string;
    state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    address: string;
    auctionDate: string;
    result: "sold_at_auction" | "sold_before_auction" | "sold_after_auction" | "passed_in" | "withdrawn";
    propertyType?: "house" | "apartment" | "unit" | "townhouse" | "villa" | "land" | "rural" | "commercial" | "other" | undefined;
    externalId?: string | undefined;
    guidePrice?: number | undefined;
    soldPrice?: number | undefined;
}>;
export type AuctionResult = z.infer<typeof AuctionResultSchema>;
export declare const MarketIndicatorSchema: z.ZodObject<{
    indicatorType: z.ZodString;
    scope: z.ZodString;
    value: z.ZodNumber;
    unit: z.ZodOptional<z.ZodString>;
    recordedAt: z.ZodString;
    source: z.ZodEnum<["DOMAIN", "REALESTATE", "CORELOGIC", "ABS", "RBA", "MANUAL"]>;
}, "strip", z.ZodTypeAny, {
    value: number;
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    indicatorType: string;
    scope: string;
    recordedAt: string;
    unit?: string | undefined;
}, {
    value: number;
    source: "DOMAIN" | "REALESTATE" | "CORELOGIC" | "ABS" | "RBA" | "MANUAL";
    indicatorType: string;
    scope: string;
    recordedAt: string;
    unit?: string | undefined;
}>;
export type MarketIndicator = z.infer<typeof MarketIndicatorSchema>;
export declare const InfrastructureProjectSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    category: z.ZodEnum<["transport", "health", "education", "commercial", "residential", "other"]>;
    status: z.ZodEnum<["announced", "planning", "construction", "completed"]>;
    state: z.ZodEnum<["NSW", "VIC", "QLD", "WA", "SA", "TAS", "NT", "ACT"]>;
    suburbs: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    estimatedCost: z.ZodOptional<z.ZodNumber>;
    completionDate: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    sourceUrl: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "announced" | "planning" | "construction" | "completed";
    state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
    name: string;
    id: string;
    category: "commercial" | "other" | "transport" | "health" | "education" | "residential";
    sourceUrl?: string | undefined;
    description?: string | undefined;
    suburbs?: string[] | undefined;
    estimatedCost?: number | undefined;
    completionDate?: string | undefined;
}, {
    status: "announced" | "planning" | "construction" | "completed";
    state: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "NT" | "ACT";
    name: string;
    id: string;
    category: "commercial" | "other" | "transport" | "health" | "education" | "residential";
    sourceUrl?: string | undefined;
    description?: string | undefined;
    suburbs?: string[] | undefined;
    estimatedCost?: number | undefined;
    completionDate?: string | undefined;
}>;
export type InfrastructureProject = z.infer<typeof InfrastructureProjectSchema>;
//# sourceMappingURL=index.d.ts.map