import { coordsToJurisdictions, coordToAUStates } from "../utils";

export const enum AustralianState {
    NSW = "NSW",
    VIC = "VIC",
    QLD = "QLD",
    WA = "WA",
    SA = "SA",
    TAS = "TAS",
    NT = "NT",
    ACT = "ACT",
}

export const enum Jurisdiction {
    TOOWOOMBA = "Toowoomba Regional Council",
    MAKAYE = "Mackay Regional Council",
}

export type Layers = "LANDIND_ZONES" | "FLOOD_HAZARD" | "BUSHFIRE_HAZARD" | "LANDSLIDE_HAZARD" | "STORM_TIDE_HAZARD" | "HERITAGE_ZONES" | "SCHOOL_ZONES";

export type Styles = {
    label: string;
    idKey: string[];
    fillColor: string;
    groupName: string;
    strokeColor?: string;
};

export interface BBBox {
    minLat: number;
    minLng: number;
    maxLat: number;
    maxLng: number;
}

export type LayerRegistry = {
    id: string;
    name: string;
    url: string;
    coverage: "state" | "lga";
    propertyKey: string[];
    labelKey: string;
    jurisdiction?: Jurisdiction;
    coverageCords?: BBBox;
    whereClause?: string;
}


export const JuridsictionCoords: Record<Jurisdiction, BBBox> = {
    [Jurisdiction.TOOWOOMBA]: {
        minLat: -28.192347,
        minLng: 150.702672,
        maxLat: -26.766807,
        maxLng: 152.251429,
    },
    [Jurisdiction.MAKAYE]: {
        minLat: -22.40,
        minLng: 147.90,
        maxLat: -20.10,
        maxLng: 150.60,
    },
};

export const StateCoords: Record<AustralianState, BBBox> = {
    [AustralianState.ACT]: { minLat: -35.92, minLng: 148.76, maxLat: -35.12, maxLng: 149.40 },
    [AustralianState.TAS]: { minLat: -43.75, minLng: 144.40, maxLat: -39.20, maxLng: 148.50 },
    [AustralianState.VIC]: { minLat: -39.20, minLng: 140.90, maxLat: -33.90, maxLng: 150.00 },
    [AustralianState.NSW]: { minLat: -37.60, minLng: 140.99, maxLat: -28.15, maxLng: 153.64 },
    [AustralianState.QLD]: { minLat: -28.20, minLng: 138.00, maxLat: -10.00, maxLng: 153.64 },
    [AustralianState.SA]: { minLat: -38.10, minLng: 129.00, maxLat: -26.00, maxLng: 141.00 },
    [AustralianState.NT]: { minLat: -26.00, minLng: 129.00, maxLat: -10.00, maxLng: 138.00 },
    [AustralianState.WA]: { minLat: -35.20, minLng: 112.90, maxLat: -13.50, maxLng: 129.00 },
};

type LayerInfo = Record<Layers, LayerRegistry | LayerRegistry[]>;

const NSW_LAYER_INFO: LayerInfo = {
    LANDIND_ZONES: {
        id: "NSW_LAND_ZONING",
        name: "NSW Land Zoning",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Planning/EPI_Primary_Planning_Layers/MapServer/2",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "EPI_NAME",
            "LGA_NAME",
            "PUBLISHED_DATE",
            "COMMENCED_DATE",
            "CURRENCY_DATE",
            "AMENDMENT",
            "MAP_TYPE",
            "MAP_NAME",
            "LAY_NAME",
            "LAY_CLASS",
            "SYM_CODE",
            "PURPOSE",
            "LEGIS_REF_AREA",
            "LEGIS_REF_CLAUSE",
            "LEGIS_REF_VALUE",
            "PCO_REF_KEY",
            "EPI_TYPE",
            "SHAPE",
        ],
        labelKey: "LAY_CLASS",
    },
    FLOOD_HAZARD: {
        id: "NSW_FLOOD_HAZARD",
        name: "NSW Flood Hazard",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Planning/Hazard/MapServer/1",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "EPI_NAME",
            "LGA_NAME",
            "PUBLISHED_DATE",
            "COMMENCED_DATE",
            "CURRENCY_DATE",
            "AMENDMENT",
            "LAY_CLASS",
            "EPI_TYPE",
            "COMMENT",
            "SHAPE",
        ],
        labelKey: "LAY_CLASS",
    },
    BUSHFIRE_HAZARD: {
        id: "NSW_BUSHFIRE_HAZARD",
        name: "NSW Bushfire Hazard",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Fire/NPWS_Fire_History/MapServer/0", // Placeholder URL as not provided
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "FireType",
            "FireName",
            "FireNo",
            "FireYear",
            "Label",
            "StartDate",
            "EndDate",
            "Intensity",
            "AreaHa",
            "PerimeterM",
            "OFHObjMet",
            "ObjNotMet",
            "NPWSBranch",
            "NPWSArea",
            "Shape",
            "VerDate",
            "Shape.STArea()",
            "Shape.STLength()",
        ],
        labelKey: "FireType",
    },
    LANDSLIDE_HAZARD: {
        id: "NSW_LANDSLIDE_HAZARD",
        name: "NSW Landslide Hazard",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Planning/Hazard/MapServer/2",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "EPI_NAME",
            "LGA_NAME",
            "PUBLISHED_DATE",
            "COMMENCED_DATE",
            "CURRENCY_DATE",
            "AMENDMENT",
            "LAY_CLASS",
            "EPI_TYPE",
            "SHAPE",
        ],
        labelKey: "LAY_CLASS",

    },
    STORM_TIDE_HAZARD: {
        id: "NSW_STORM_TIDE_HAZARD",
        name: "NSW Storm Tide Hazard",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Hazards/Storm_Tide_Hazard/MapServer/0",  // Placeholder URL as not provided
        coverage: "state",
        propertyKey: [],
        labelKey: "",
    },
    HERITAGE_ZONES: {
        id: "NSW_HERITAGE_ZONES",
        name: "NSW Heritage Zones",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Planning/EPI_Primary_Planning_Layers/MapServer/0",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "EPI_NAME",
            "LGA_NAME",
            "PUBLISHED_DATE",
            "COMMENCED_DATE",
            "CURRENCY_DATE",
            "AMENDMENT",
            "MAP_TYPE",
            "MAP_NAME",
            "LAY_NAME",
            "LAY_CLASS",
            "H_ID",
            "H_NAME",
            "SIG",
            "LEGIS_REF_CLAUSE",
            "PCO_REF_KEY",
            "EPI_TYPE",
            "SHAPE",
        ],
        labelKey: "LAY_CLASS",
    },
    SCHOOL_ZONES: {
        id: "NSW_SCHOOL_ZONES",
        name: "NSW School Zones",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/HMS/Heritage/MapServer/0",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "TOPOID",
            "POIGROUP",
            "POITYPE",
            "POINAME",
            "POILABEL",
            "POILABELTYPE",
            "POIALTLABEL",
            "POISOURCEFEATUREOID",
            "STARTDATE",
            "ENDDATE",
            "LASTUPDATE",
            "ACCESSCONTROL",
            "PACKETID",
            "ISPROCESSED",
            "RECORDSTATUS",
            "SHAPE",
        ],
        labelKey: "POITYPE",
        whereClause: "POITYPE IN ('Academy','University', 'Education Facility', 'Preschool', 'Primary School', 'TAFE College')",
    }
}

const QLD_LAYER_INFO: LayerInfo = {
    LANDIND_ZONES: [
        {
            id: "QLD_LAND_ZONING",
            name: "QLD Land Zoning",
            url: "https://spatial-gis.information.qld.gov.au/arcgis/rest/services/PlanningCadastre/LandUse/MapServer/0",
            coverage: "state",
            propertyKey: [
                "objectid",
                "year",
                "qlump_code",
                "alum_code",
                "secondary",
                "tertiary",
                "commodity",
                "management",
                "ruleid",
                "shape",
                "st_area(shape)",
                "st_perimeter(shape)",
                "primary_",
            ],
            labelKey: "qlump_code",
        }
    ],
    FLOOD_HAZARD: [
        {
            id: "QLD_FLOOD_HAZARD",
            name: "QLD Flood Hazard",
            url: "https://spatial-gis.information.qld.gov.au/arcgis/rest/services/Boundaries/AdminBoundariesFramework/MapServer/15",
            coverage: "state",
            propertyKey: [
                "objectid",
                "sub_name",
                "sub_number",
                "qra_supply",
                "sub_name2",
                "version",
                "currency",
                "globalid",
                "shape",
                "st_area(shape)",
                "st_perimeter(shape)",
            ],
            labelKey: "sub_name",
        }
    ],
    BUSHFIRE_HAZARD: [
        {
            id: "QLD_BUSHFIRE_HAZARD",
            name: "QLD Bushfire Hazard",
            url: "https://spatial-gis.information.qld.gov.au/arcgis/rest/services/Boundaries/AdminBoundariesFramework/MapServer/14",
            coverage: "state",
            propertyKey: [
                "objectid",
                "zone",
                "subzone",
                "frequency",
                "freqmin",
                "freqmax",
                "description",
                "status",
                "source",
                "src_comment",
                "vetting",
                "pos_acc",
                "shape",
                "st_area(shape)",
                "st_perimeter(shape)",
            ],
            labelKey: "zone",
        }
    ],
    LANDSLIDE_HAZARD: {
        id: "QLD_LANDSLIDE_HAZARD",
        name: "QLD Landslide Hazard",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Hazards/Landslide_Hazard/MapServer/0",  // Placeholder URL as not provided
        coverage: "state",
        propertyKey: [],
        labelKey: "",
    },
    STORM_TIDE_HAZARD: {
        id: "QLD_STORM_TIDE_HAZARD",
        name: "QLD Storm Tide Hazard",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Hazards/Storm_Tide_Hazard/MapServer/0",  // Placeholder URL as not provided
        coverage: "state",
        propertyKey: [],
        labelKey: "",
    },
    HERITAGE_ZONES: {
        id: "QLD_HERITAGE_ZONES",
        name: "QLD Heritage Zones",
        url: "https://spatial-gis.information.qld.gov.au/arcgis/rest/services/Boundaries/AdminBoundariesFramework/MapServer/78",
        coverage: "state",
        propertyKey: [
            "placename",
            "place_id",
            "entrydate",
            "area_sqm",
            "accuracy",
            "status",
            "objectid",
            "shape",
        ],
        labelKey: "placename",
    },
    SCHOOL_ZONES: [
        {
            id: "QLD_SCHOOL_ZONES_PRIMARY_STATE_SCHOOLS",
            name: "QLD School Zones - Primary State Schools",
            url: "https://spatial-gis.information.qld.gov.au/arcgis/rest/services/Society/SchoolsAndSchoolCatchments/MapServer/4",
            coverage: "state",
            propertyKey: [
                "centre_name",
                "centre_code",
                "source",
                "data_currency",
                "disclaimer",
                "shape",
                "objectid",
            ],
            labelKey: "centre_name",
        },
        {
            id: "QLD_SCHOOL_ZONES_JUNIOR_SECONDARY_STATE_SCHOOLS",
            name: "QLD School Zones - Junior Secondary State Schools",
            url: "https://spatial-gis.information.qld.gov.au/arcgis/rest/services/Society/SchoolsAndSchoolCatchments/MapServer/5",
            coverage: "state",
            propertyKey: [
                "centre_name",
                "centre_code",
                "source",
                "data_currency",
                "disclaimer",
                "shape",
                "objectid",
            ],
            labelKey: "centre_name",
        },
        {
            id: "QLD_SCHOOL_ZONES_SENIOR_SECONDARY_STATE_SCHOOLS",
            name: "QLD School Zones - Senior Secondary State Schools",
            url: "https://spatial-gis.information.qld.gov.au/arcgis/rest/services/Society/SchoolsAndSchoolCatchments/MapServer/6",
            coverage: "state",
            propertyKey: [
                "centre_name",
                "centre_code",
                "source",
                "data_currency",
                "disclaimer",
                "shape",
                "objectid",
            ],
            labelKey: "centre_name",
        },
        {
            id: "QLD_SCHOOL_ZONES_SPECIAL_STATE_SCHOOLS",
            name: "QLD School Zones - Special State Schools",
            url: "https://spatial-gis.information.qld.gov.au/arcgis/rest/services/Society/SchoolsAndSchoolCatchments/MapServer/8",
            coverage: "state",
            propertyKey: [
                "centre_name",
                "centre_code",
                "source",
                "data_currency",
                "disclaimer",
                "shape",
                "objectid",
            ],
            labelKey: "centre_name",
        },
        {
            id: "QLD_SCHOOL_ZONES_NON_STATE_SCHOOLS",
            name: "QLD School Zones - Non-State Schools",
            url: "https://spatial-gis.information.qld.gov.au/arcgis/rest/services/Society/SchoolsAndSchoolCatchments/MapServer/9",
            coverage: "state",
            propertyKey: [
                "centre_name",
                "centre_code",
                "source",
                "data_currency",
                "disclaimer",
                "shape",
                "objectid",
            ],
            labelKey: "centre_name",
        }
    ]
}

// Western Australia Layer Configuration
const WA_LAYER_INFO: LayerInfo = {
    LANDIND_ZONES: {
        id: "WA_LAND_ZONING",
        name: "WA Land Zoning",
        url: "https://public-services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Property_and_Planning/MapServer/112",
        coverage: "state",
        propertyKey: [
            "objectid",
            "zone_numbe",
            "zone",
            "add_label",
            "rest_label",
            "specadd_la",
            "special_la",
            "label",
            "label_desc",
            "gazettal_d",
            "scheme_nam",
            "lga",
            "scheme_no",
            "shape",
        ],
        labelKey: "zone",
    },
    FLOOD_HAZARD: {
        id: "WA_FLOOD_HAZARD",
        name: "WA Flood Hazard (Climate Projections)",
        url: "https://public-services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Water/MapServer/57",
        coverage: "state",
        propertyKey: [
            "objectid",
            "event",
            "est_ari",
            "hyd_name",
            "location",
            "vert_datum",
            "date_check",
            "source",
            "comments",
            "ufi",
            "crt_date",
            "src_date",
            "edit_by",
            "auth_by",
            "cap_meth",
            "cap_scale",
            "shape",
            "st_area(shape)",
            "st_perimeter(shape)",
        ],
        labelKey: "hyd_name",
    },
    BUSHFIRE_HAZARD: {
        id: "WA_BUSHFIRE_HAZARD",
        name: "WA Bushfire Prone Areas",
        url: "https://public-services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Bush_Fire_Prone_Areas/MapServer/17",
        coverage: "state",
        propertyKey: [
            "designation",
            "lga",
            "objectid",
            "type",
            "designationdate",
            "shape",
            "st_area(shape)",
            "st_perimeter(shape)",
        ],
        labelKey: "designation",
    },
    LANDSLIDE_HAZARD: {
        id: "WA_LANDSLIDE_HAZARD",
        name: "WA Landslide Hazard",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Hazards/Landslide_Hazard/MapServer/0", // Placeholder - no WA specific data
        coverage: "state",
        propertyKey: [],
        labelKey: "",
    },
    STORM_TIDE_HAZARD: {
        id: "WA_STORM_TIDE_HAZARD",
        name: "WA Storm Tide Hazard",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Hazards/Storm_Tide_Hazard/MapServer/0", // Placeholder - no WA specific data
        coverage: "state",
        propertyKey: [],
        labelKey: "",
    },
    HERITAGE_ZONES: {
        id: "WA_HERITAGE_ZONES",
        name: "WA Heritage Register",
        url: "https://public-services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/People_and_Society/MapServer/16",
        coverage: "state",
        propertyKey: [
            "objectid",
            "place_no",
            "place_name",
            "location",
            "lga",
            "more_info",
            "shape_leng",
            "shape",
            "st_area(shape)",
            "st_perimeter(shape)",
        ],
        labelKey: "place_name",
    },
    SCHOOL_ZONES: {
        id: "WA_SCHOOL_ZONES",
        name: "WA School Zones",
        url: "https://public-services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Property_and_Planning/MapServer/112",
        coverage: "state",
        propertyKey: [
            "objectid",
            "zone_numbe",
            "zone",
            "add_label",
            "rest_label",
            "specadd_la",
            "special_la",
            "label",
            "label_desc",
            "gazettal_d",
            "scheme_nam",
            "lga",
            "scheme_no",
            "shape",
        ],
        labelKey: "zone",
        whereClause: "zone in ('Education', 'School', 'Educational')",
    }
}

// South Australia Layer Configuration
const SA_LAYER_INFO: LayerInfo = {
    LANDIND_ZONES: {
        id: "SA_LAND_ZONING",
        name: "SA Land Zoning",
        url: "https://location.sa.gov.au/server6/rest/services/ePlanningPublic/CurrentPDC_wmas/MapServer/114",
        coverage: "state",
        propertyKey: [
            "objectid",
            "id",
            "name",
            "description",
            "value",
            "legalstartdate",
            "legalenddate",
            "systemstartdate",
            "systemenddate",
            "status",
            "shape",
            "st_area(shape)",
            "st_length(shape)",
        ],
        labelKey: "name",
    },
    FLOOD_HAZARD: {
        id: "SA_FLOOD_HAZARD",
        name: "SA Flood Hazard Zones",
        url: "https://location.sa.gov.au/server6/rest/services/ePlanningPublic/ConsultFlooding/MapServer/7",
        coverage: "state",
        propertyKey: [
            "objectid",
            "id",
            "name",
            "description",
            "value",
            "legalstartdate",
            "legalenddate",
            "systemstartdate",
            "systemenddate",
            "status",
            "shape",
            "st_area(shape)",
            "st_length(shape)",
        ],
        labelKey: "name",
    },
    BUSHFIRE_HAZARD: [
        {
            id: "SA_BUSHFIRE_HAZARD_HIGH_RISK",
            name: "SA Bushfire Hazard Zones - (High Risk Areas)",
            url: "https://location.sa.gov.au/server6/rest/services/ePlanningPublic/CurrentPDC_wmas/MapServer/10",
            coverage: "state",
            propertyKey: [
                "objectid",
                "id",
                "name",
                "description",
                "value",
                "legalstartdate",
                "legalenddate",
                "systemstartdate",
                "systemenddate",
                "status",
                "shape",
                "st_area(shape)",
                "st_length(shape)",
            ],
            labelKey: "name",
        },
        {
            id: "SA_BUSHFIRE_HAZARD_MEDIUM_RISK",
            name: "SA Bushfire Hazard Zones - (Medium Risk Areas)",
            url: "https://gis.environment.gov.au/gispubmap/rest/services/ogc_services/World_Heritage_Areas/MapServer/0",
            coverage: "state",
            propertyKey: [
                "objectid",
                "id",
                "name",
                "description",
                "value",
                "legalstartdate",
                "legalenddate",
                "systemstartdate",
                "systemenddate",
                "status",
                "shape",
                "st_area(shape)",
                "st_length(shape)",
            ],
            labelKey: "name",
        },
        {
            id: "SA_BUSHFIRE_HAZARD_GENERAL_RISK",
            name: "SA Bushfire Hazard Zones - (General Risk Areas)",
            url: "https://gis.environment.gov.au/gispubmap/rest/services/ogc_services/World_Heritage_Areas/MapServer/0",
            coverage: "state",
            propertyKey: [
                "objectid",
                "id",
                "name",
                "description",
                "value",
                "legalstartdate",
                "legalenddate",
                "systemstartdate",
                "systemenddate",
                "status",
                "shape",
                "st_area(shape)",
                "st_length(shape)",
            ],
            labelKey: "name",
        },
    ],
    LANDSLIDE_HAZARD: {
        id: "SA_LANDSLIDE_HAZARD",
        name: "SA Landslide Hazard Zones",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Hazards/Landslide_Hazard/MapServer/0", // Placeholder
        coverage: "state",
        propertyKey: [],
        labelKey: "",
    },
    STORM_TIDE_HAZARD: {
        id: "SA_STORM_TIDE_HAZARD",
        name: "SA Storm Tide Hazard Zones",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Hazards/Storm_Tide_Hazard/MapServer/0", // Placeholder
        coverage: "state",
        propertyKey: [],
        labelKey: "",
    },
    HERITAGE_ZONES: {
        id: "SA_HERITAGE_ZONES",
        name: "SA Heritage Zones",
        url: "https://location.sa.gov.au/server6/rest/services/ePlanningPublic/CurrentPDC_wmas/MapServer/23",
        coverage: "state",
        propertyKey: [
            "objectid",
            "id",
            "name",
            "description",
            "value",
            "legalstartdate",
            "legalenddate",
            "systemstartdate",
            "systemenddate",
            "status",
            "shape",
            "st_area(shape)",
            "st_length(shape)",
        ],
        labelKey: "name",
    },
    SCHOOL_ZONES: {
        id: "SA_SCHOOL_ZONES",
        name: "SA School Zones",
        coverage: "state",
        url: "https://location.sa.gov.au/server6/rest/services/Transport/ElectricalAssets/MapServer/4",
        propertyKey: [
            "objectid",
            "site_type",
            "site_no",
            "site_desc",
            "road_no",
            "rrd_ul",
            "rrd_r",
            "suburb",
            "school_name",
            "shape",
            "resp",
        ],
        labelKey: "school_name",
    }
}

// Australian Capital Territory Layer Configuration
const ACT_LAYER_INFO: LayerInfo = {
    LANDIND_ZONES: {
        id: "ACT_LAND_ZONING",
        name: "ACT Landscape Area Assets",
        url: "https://services1.arcgis.com/E5n4f1VY84i0xSjy/ArcGIS/rest/services/ACTGOV_TP_LAND_USE_ZONE/FeatureServer/1",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "ID",
            "VARIATION_NUMBER_CREATED_BY",
            "VARIATION_YEAR",
            "GAZETTAL_NUMBER",
            "GAZETTAL_DATE",
            "DESCRIPTION",
            "LAND_USE_ZONE_CODE_ID",
            "LAND_USE_POLICY_DESC",
            "CURRENT_LIFECYCLE_STAGE",
            "DEGAZETTAL_NUMBER",
            "DIVISION_SHORT",
            "DIVISION_CODE",
            "DIVISION_NAME",
            "DISTRICT_SHORT",
            "DISTRICT_CODE",
            "DISTRICT_NAME",
            "Shape__Area",
            "Shape__Length",
        ],
        labelKey: "LAND_USE_ZONE_CODE_ID",
    },
    FLOOD_HAZARD: {
        id: "ACT_FLOOD_HAZARD",
        name: "ACT Flood Extent",
        url: "https://services1.arcgis.com/E5n4f1VY84i0xSjy/ArcGIS/rest/services/ACTGOV_FLOOD_EXTENT/FeatureServer/0",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "FLOOD_TYPE",
            "FLOOD_ZONE",
            "DESCRIPTION",
            "GlobalID",
            "Shape__Area",
            "Shape__Length",
        ],
        labelKey: "FLOOD_ZONE",
    },
    BUSHFIRE_HAZARD: {
        id: "ACT_BUSHFIRE_HAZARD",
        name: "ACT Fire Management Zones",
        url: "https://services1.arcgis.com/E5n4f1VY84i0xSjy/ArcGIS/rest/services/Fire_Management_Zones_2015_2019/FeatureServer/0",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "ID",
            "ELEM_TEXT",
            "DESC_",
            "Hectare",
            "Shape__Area",
            "Shape__Length",
            "Shape__Area_2",
            "Shape__Length_2",
        ],
        labelKey: "ELEM_TEXT",
    },
    LANDSLIDE_HAZARD: {
        id: "ACT_LANDSLIDE_HAZARD",
        name: "ACT Landslide Hazard",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Hazards/Landslide_Hazard/MapServer/0", // Placeholder
        coverage: "state",
        propertyKey: [],
        labelKey: "",
    },
    STORM_TIDE_HAZARD: {
        id: "ACT_STORM_TIDE_HAZARD",
        name: "ACT Storm Tide Hazard",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Hazards/Storm_Tide_Hazard/MapServer/0", // Placeholder
        coverage: "state",
        propertyKey: [],
        labelKey: "",
    },
    HERITAGE_ZONES: {
        id: "ACT_HERITAGE_ZONES",
        name: "ACT Heritage Register",
        url: "https://services1.arcgis.com/E5n4f1VY84i0xSjy/ArcGIS/rest/services/ACTGOV_Heritage_Register/FeatureServer/1",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "BLOCK_NUMBER",
            "SECTION_NUMBER",
            "LAND_USE_POLICY_ZONES",
            "OVERLAY_PROVISION_ZONES",
            "DIVISION_CODE",
            "DIVISION_NAME",
            "DIVISION_SHORT",
            "DISTRICT_CODE",
            "DISTRICT_NAME",
            "DISTRICT_SHORT",
            "NAME",
            "SITE_NAME",
            "DataRestrictions",
            "HRcategory",
            "HRcode",
            "HeritageID",
            "HRstatus",
            "last_edited_user",
            "last_edited_date",
            "created_user",
            "created_date",
            "Shape__Area",
            "Shape__Length",
        ],
        labelKey: "NAME",
    },
    SCHOOL_ZONES: {
        id: "ACT_SCHOOL_ZONES",
        name: "ACT School Zones",
        url: "https://services1.arcgis.com/E5n4f1VY84i0xSjy/ArcGIS/rest/services/ACTGOV_School_Location_Current/FeatureServer/0",
        coverage: "state",
        propertyKey: [
            "id",
            "ACTmapi_FeatureName",
            "SCHOOL_NAME",
            "DESCRIPTION",
            "WEBSITE",
            "EMAIL",
            "PHONE",
            "MY_SCHOOL_WEBSITE",
            "YEAR_LEVEL",
            "APPLY_NOW",
            "GOVERNMENT",
            "TYPE",
            "PEA",
            "STREET",
            "SUBURB",
            "STATE",
            "POSTCODE",
            "SCHOOL_CODE",
        ],
        labelKey: "SCHOOL_NAME",
    }
}

// Victoria Layer Configuration
const VIC_LAYER_INFO: LayerInfo = {
    LANDIND_ZONES: [
        {
            id: "VIC_LAND_ZONING_LOW_DENSITY_RESIDENTIAL",
            name: "VIC Land Zoning - Low Density Residential",
            url: "https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Vicplan_PlanningSchemeZones/MapServer/3",
            coverage: "state",
            propertyKey: [
                "OBJECTID",
                "Shape",
                "PFI",
                "SCHEME_CODE",
                "LGA_CODE",
                "LGA",
                "ZONE_NUM",
                "ZONE_STATUS",
                "ZONE_CODE",
                "ZONE_DESCRIPTION",
                "GAZ_BEGIN_DATE",
                "PFI_CREATED",
                "UFI",
                "UFI_CREATED",
                "ZONE_CODE_GROUP",
                "ZONE_CODE_GROUP_LABEL",
                "Shape_Length",
                "Shape_Area",
            ],
            labelKey: "ZONE_CODE_GROUP_LABEL",
        },
        {
            id: "VIC_LAND_ZONING_MIXED_USE",
            name: "VIC Land Zoning - Mixed Use Zone",
            url: "https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Vicplan_PlanningSchemeZones/MapServer/4",
            coverage: "state",
            propertyKey: [
                "OBJECTID",
                "Shape",
                "PFI",
                "SCHEME_CODE",
                "LGA_CODE",
                "LGA",
                "ZONE_NUM",
                "ZONE_STATUS",
                "ZONE_CODE",
                "ZONE_DESCRIPTION",
                "GAZ_BEGIN_DATE",
                "PFI_CREATED",
                "UFI",
                "UFI_CREATED",
                "ZONE_CODE_GROUP",
                "ZONE_CODE_GROUP_LABEL",
                "Shape_Length",
                "Shape_Area",
            ],
            labelKey: "ZONE_CODE_GROUP_LABEL",
        },
        {
            id: "VIC_LAND_ZONING_TOWNSHIP",
            name: "VIC Land Zoning - Township Zone",
            url: "https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Vicplan_PlanningSchemeZones/MapServer/5",
            coverage: "state",
            propertyKey: [
                "OBJECTID",
                "Shape",
                "PFI",
                "SCHEME_CODE",
                "LGA_CODE",
                "LGA",
                "ZONE_NUM",
                "ZONE_STATUS",
                "ZONE_CODE",
                "ZONE_DESCRIPTION",
                "GAZ_BEGIN_DATE",
                "PFI_CREATED",
                "UFI",
                "UFI_CREATED",
                "ZONE_CODE_GROUP",
                "ZONE_CODE_GROUP_LABEL",
                "Shape_Length",
                "Shape_Area",
            ],
            labelKey: "ZONE_CODE_GROUP_LABEL",
        },
        {
            id: "VIC_LAND_ZONING_RESIDENTIAL_GROWTH",
            name: "VIC Land Zoning - Residential Growth Zone",
            url: "https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Vicplan_PlanningSchemeZones/MapServer/6",
            coverage: "state",
            propertyKey: [
                "OBJECTID",
                "Shape",
                "PFI",
                "SCHEME_CODE",
                "LGA_CODE",
                "LGA",
                "ZONE_NUM",
                "ZONE_STATUS",
                "ZONE_CODE",
                "ZONE_DESCRIPTION",
                "GAZ_BEGIN_DATE",
                "PFI_CREATED",
                "UFI",
                "UFI_CREATED",
                "ZONE_CODE_GROUP",
                "ZONE_CODE_GROUP_LABEL",
                "Shape_Length",
                "Shape_Area",
            ],
            labelKey: "ZONE_CODE_GROUP_LABEL",
        },
        {
            id: "VIC_LAND_ZONING_NEIGHBOURHOOD_RESIDENTIAL",
            name: "VIC Land Zoning - Neighbourhood Residential Zone",
            url: "https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Vicplan_PlanningSchemeZones/MapServer/7",
            coverage: "state",
            propertyKey: [
                "OBJECTID",
                "Shape",
                "PFI",
                "SCHEME_CODE",
                "LGA_CODE",
                "LGA",
                "ZONE_NUM",
                "ZONE_STATUS",
                "ZONE_CODE",
                "ZONE_DESCRIPTION",
                "GAZ_BEGIN_DATE",
                "PFI_CREATED",
                "UFI",
                "UFI_CREATED",
                "ZONE_CODE_GROUP",
                "ZONE_CODE_GROUP_LABEL",
                "Shape_Length",
                "Shape_Area",
            ],
            labelKey: "ZONE_CODE_GROUP_LABEL",
        },
        {
            id: "VIC_LAND_ZONING_GENERAL_RESIDENTIAL",
            name: "VIC Land Zoning - General Residential Zone",
            url: "https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Vicplan_PlanningSchemeZones/MapServer/8",
            coverage: "state",
            propertyKey: [
                "OBJECTID",
                "Shape",
                "PFI",
                "SCHEME_CODE",
                "LGA_CODE",
                "LGA",
                "ZONE_NUM",
                "ZONE_STATUS",
                "ZONE_CODE",
                "ZONE_DESCRIPTION",
                "GAZ_BEGIN_DATE",
                "PFI_CREATED",
                "UFI",
                "UFI_CREATED",
                "ZONE_CODE_GROUP",
                "ZONE_CODE_GROUP_LABEL",
                "Shape_Length",
                "Shape_Area",
            ],
            labelKey: "ZONE_CODE_GROUP_LABEL",
        },
    ],
    FLOOD_HAZARD: {
        id: "VIC_FLOOD_HAZARD",
        name: "VIC Flood Hazard",
        url: "https://emapdev.ffm.vic.gov.au/arcgis/rest/services/Victorian_Flood_Database/MapServer/13",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "HEIGHT",
            "STUDYID",
            "ARI",
            "STUDYARI",
            "METHOD",
            "RELIABILITY",
            "PLAN_NO",
            "NOTE_CODE",
            "TYPE",
            "LENGTH",
            "MODIFIED",
            "VERSION",
            "SHAPE",
            "SHAPE.STLength()",
        ],
        labelKey: "METHOD",
    },
    BUSHFIRE_HAZARD: {
        id: "VIC_BUSHFIRE_HAZARD",
        name: "VIC Bushfire Hazard (LGA)",
        url: "https://emapdev.ffm.vic.gov.au/arcgis/rest/services/vsw_fire_management/MapServer/47",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "FIRETYPE",
            "SEASON",
            "FIRE_NO",
            "NAME",
            "START_DATE",
            "FIREKEY",
            "AREA_HA",
            "DSE_ID",
            "CFA_ID",
            "SHAPE",
            "SHAPE.STArea()",
            "SHAPE.STLength()",
            "START_DATE_INT",
            "TREATMENT_TYPE",
        ],
        labelKey: "NAME",
    },
    LANDSLIDE_HAZARD: {
        id: "VIC_LANDSLIDE_HAZARD",
        name: "VIC Landslide Hazard",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Hazards/Landslide_Hazard/MapServer/0", // Placeholder
        coverage: "state",
        propertyKey: [],
        labelKey: "",
    },
    STORM_TIDE_HAZARD: {
        id: "VIC_STORM_TIDE_HAZARD",
        name: "VIC Storm Tide Hazard",
        url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Hazards/Storm_Tide_Hazard/MapServer/0", // Placeholder
        coverage: "state",
        propertyKey: [],
        labelKey: "",
    },
    HERITAGE_ZONES: {
        id: "VIC_HERITAGE_ZONES",
        name: "VIC Heritage Zones",
        url: "https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Vicplan_PlanningSchemeOverlays/MapServer/9",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "Shape",
            "PFI",
            "SCHEME_CODE",
            "LGA_CODE",
            "LGA",
            "ZONE_NUM",
            "ZONE_STATUS",
            "ZONE_CODE",
            "ZONE_DESCRIPTION",
            "GAZ_BEGIN_DATE",
            "PFI_CREATED",
            "UFI",
            "UFI_CREATED",
            "ZONE_CODE_GROUP",
            "ZONE_CODE_GROUP_LABEL",
            "Shape_Length",
            "Shape_Area",
        ],
        labelKey: "SCHEME_CODE",
    },
    SCHOOL_ZONES: {
        id: "VIC_SCHOOL_ZONES",
        name: "VIC School Zones",
        url: "https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Vicplan_PlanningSchemeZones/MapServer/31",
        coverage: "state",
        propertyKey: [
            "OBJECTID",
            "Shape",
            "PFI",
            "SCHEME_CODE",
            "LGA_CODE",
            "LGA",
            "ZONE_NUM",
            "ZONE_STATUS",
            "ZONE_CODE",
            "ZONE_DESCRIPTION",
            "GAZ_BEGIN_DATE",
            "PFI_CREATED",
            "UFI",
            "UFI_CREATED",
            "ZONE_CODE_GROUP",
            "ZONE_CODE_GROUP_LABEL",
            "Shape_Length",
            "Shape_Area",
        ],
        labelKey: "ZONE_CODE_GROUP_LABEL",
    }
}

export const LayerInfoLabelNames: Record<Layers, string[]> = {
    LANDIND_ZONES: ["LAY_CLASS", "tertiary"],
    FLOOD_HAZARD: ["LAY_CLASS", "sub_name"],
    BUSHFIRE_HAZARD: ["zone", "FireType"],
    LANDSLIDE_HAZARD: ["LAY_CLASS"],
    STORM_TIDE_HAZARD: ["LAY_CLASS"],
    HERITAGE_ZONES: ["LAY_CLASS", "placename"],
    SCHOOL_ZONES: ["POITYPE", "centre_name", "SCHOOL_NAME"],
}

export const stateLayerMapping: Record<AustralianState, LayerInfo> = {
    [AustralianState.NSW]: NSW_LAYER_INFO,
    [AustralianState.VIC]: VIC_LAYER_INFO,
    [AustralianState.QLD]: QLD_LAYER_INFO,
    [AustralianState.WA]: WA_LAYER_INFO,
    [AustralianState.SA]: SA_LAYER_INFO,
    [AustralianState.TAS]: NSW_LAYER_INFO, // Tasmania still uses NSW as fallback
    [AustralianState.NT]: NSW_LAYER_INFO, // Northern Territory still uses NSW as fallback
    [AustralianState.ACT]: ACT_LAYER_INFO,
}

export const getLayersForView = (view: BBBox, layer: Layers): LayerRegistry[] => {
    const statesInView = coordToAUStates(view);
    const lgasInView = coordsToJurisdictions(view);

    const layers: LayerRegistry[] = [];

    statesInView.forEach((state) => {
        const layerInfo = stateLayerMapping[state][layer];
        if (Array.isArray(layerInfo)) {
            layerInfo.forEach((layerItem) => {
                if (layerItem.coverage === "state") {
                    layers.push(layerItem);
                }
                else if (layerItem.coverage === "lga" && layerItem.jurisdiction && lgasInView.includes(layerItem.jurisdiction)) {
                    layers.push(layerItem);
                }
            });
        }
        else {
            layers.push(layerInfo);
        }
    });
    return layers;
}